//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_application.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobile_application.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About app.
        /// </summary>
        internal static string ButtonAboutApp {
            get {
                return ResourceManager.GetString("ButtonAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add ingredient.
        /// </summary>
        internal static string ButtonAddIngredient {
            get {
                return ResourceManager.GetString("ButtonAddIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add ingredient type.
        /// </summary>
        internal static string ButtonAddIngredientType {
            get {
                return ResourceManager.GetString("ButtonAddIngredientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add order.
        /// </summary>
        internal static string ButtonAddOrder {
            get {
                return ResourceManager.GetString("ButtonAddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add product.
        /// </summary>
        internal static string ButtonAddProduct {
            get {
                return ResourceManager.GetString("ButtonAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add product type.
        /// </summary>
        internal static string ButtonAddProductType {
            get {
                return ResourceManager.GetString("ButtonAddProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add to cart.
        /// </summary>
        internal static string ButtonAddToCart {
            get {
                return ResourceManager.GetString("ButtonAddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feedback.
        /// </summary>
        internal static string ButtonFeedback {
            get {
                return ResourceManager.GetString("ButtonFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get SMS code.
        /// </summary>
        internal static string ButtonGetSmsCode {
            get {
                return ResourceManager.GetString("ButtonGetSmsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ingredients.
        /// </summary>
        internal static string ButtonIngredients {
            get {
                return ResourceManager.GetString("ButtonIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ingredients types.
        /// </summary>
        internal static string ButtonIngredientTypes {
            get {
                return ResourceManager.GetString("ButtonIngredientTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        internal static string ButtonLogout {
            get {
                return ResourceManager.GetString("ButtonLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Orders.
        /// </summary>
        internal static string ButtonOrders {
            get {
                return ResourceManager.GetString("ButtonOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay.
        /// </summary>
        internal static string ButtonPay {
            get {
                return ResourceManager.GetString("ButtonPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Products.
        /// </summary>
        internal static string ButtonProducts {
            get {
                return ResourceManager.GetString("ButtonProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Categories.
        /// </summary>
        internal static string ButtonProductTypes {
            get {
                return ResourceManager.GetString("ButtonProductTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retry sending.
        /// </summary>
        internal static string ButtonRetrySending {
            get {
                return ResourceManager.GetString("ButtonRetrySending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select ingredient.
        /// </summary>
        internal static string ButtonSelectIngredient {
            get {
                return ResourceManager.GetString("ButtonSelectIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CreationDate.
        /// </summary>
        internal static string LabelCreationDate {
            get {
                return ResourceManager.GetString("LabelCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer.
        /// </summary>
        internal static string LabelCustomer {
            get {
                return ResourceManager.GetString("LabelCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Docs and terms.
        /// </summary>
        internal static string LabelDocsAndTerms {
            get {
                return ResourceManager.GetString("LabelDocsAndTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We&apos;ll call you when the order is ready. And let you know about new offers..
        /// </summary>
        internal static string LabelEmailforreceipts {
            get {
                return ResourceManager.GetString("LabelEmailforreceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee.
        /// </summary>
        internal static string LabelEmployee {
            get {
                return ResourceManager.GetString("LabelEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notifications.
        /// </summary>
        internal static string LabelNotifications {
            get {
                return ResourceManager.GetString("LabelNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order items.
        /// </summary>
        internal static string LabelOrderItems {
            get {
                return ResourceManager.GetString("LabelOrderItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order status.
        /// </summary>
        internal static string LabelOrderStatus {
            get {
                return ResourceManager.GetString("LabelOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total:.
        /// </summary>
        internal static string LabelOrderTotal {
            get {
                return ResourceManager.GetString("LabelOrderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your phone number.
        /// </summary>
        internal static string LabelPhoneNumber {
            get {
                return ResourceManager.GetString("LabelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit category.
        /// </summary>
        internal static string LabelProductTypeEditWindow {
            get {
                return ResourceManager.GetString("LabelProductTypeEditWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selelected ingredients.
        /// </summary>
        internal static string LabelSelectedIngredients {
            get {
                return ResourceManager.GetString("LabelSelectedIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select ingredient.
        /// </summary>
        internal static string LabelSelectIngedientToAdd {
            get {
                return ResourceManager.GetString("LabelSelectIngedientToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shopping cart items.
        /// </summary>
        internal static string LabelShoppngCartList {
            get {
                return ResourceManager.GetString("LabelShoppngCartList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMS-code sent to your number.
        /// </summary>
        internal static string LabelSMSSent {
            get {
                return ResourceManager.GetString("LabelSMSSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 00:59.
        /// </summary>
        internal static string LabelTimerDefault {
            get {
                return ResourceManager.GetString("LabelTimerDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Categories list:.
        /// </summary>
        internal static string lblPoductTypes {
            get {
                return ResourceManager.GetString("lblPoductTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page customer product.
        /// </summary>
        internal static string PageCustomerProductTitle {
            get {
                return ResourceManager.GetString("PageCustomerProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page order customer.
        /// </summary>
        internal static string PageOrderCustomerTitle {
            get {
                return ResourceManager.GetString("PageOrderCustomerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your email.
        /// </summary>
        internal static string PlaceholderEmail {
            get {
                return ResourceManager.GetString("PlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter SMS code.
        /// </summary>
        internal static string PlaceholderEnterSMS {
            get {
                return ResourceManager.GetString("PlaceholderEnterSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your name.
        /// </summary>
        internal static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your number.
        /// </summary>
        internal static string PlaceholderPhone {
            get {
                return ResourceManager.GetString("PlaceholderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter category title.
        /// </summary>
        internal static string PlaceholderProductTypeTitle {
            get {
                return ResourceManager.GetString("PlaceholderProductTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ingredients.
        /// </summary>
        internal static string TitlePageIngredients {
            get {
                return ResourceManager.GetString("TitlePageIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ingredients types.
        /// </summary>
        internal static string TitlePageIngredientTypes {
            get {
                return ResourceManager.GetString("TitlePageIngredientTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit order.
        /// </summary>
        internal static string TitlePageOrderEdit {
            get {
                return ResourceManager.GetString("TitlePageOrderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Orders.
        /// </summary>
        internal static string TitlePageOrders {
            get {
                return ResourceManager.GetString("TitlePageOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Products.
        /// </summary>
        internal static string TitlePageProducts {
            get {
                return ResourceManager.GetString("TitlePageProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product types.
        /// </summary>
        internal static string TitlePageProductTypes {
            get {
                return ResourceManager.GetString("TitlePageProductTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMS Code Verification.
        /// </summary>
        internal static string TitleSMSCodeVerification {
            get {
                return ResourceManager.GetString("TitleSMSCodeVerification", resourceCulture);
            }
        }
    }
}
